require("scripts.Panel.Panel")
require("scripts.Panel.Panel-10")
require("scripts.Panel.Panel-11")
require("scripts.Panel.Panel-18")
require("scripts.Panel.Panel-35")
require("scripts.Panel.Panel-boss")
require("scripts.Panel.Vip")