require("scripts.Mon.mon1")
require("scripts.Mon.mon2")
require("scripts.Mon.mon5")
require("scripts.Mon.mon8")
require("scripts.Mon.mon10")
require("scripts.Mon.mon12")

require("scripts.Mon.mon13")
require("scripts.Mon.mon14")
require("scripts.Mon.mon15")


require("scripts.Mon.mon16")
require("scripts.Mon.mon17")
require("scripts.Mon.mon18")
require("scripts.Mon.mon19")
require("scripts.Mon.mon22")
require("scripts.Mon.mon24")
require("scripts.Mon.mon26")
require("scripts.Mon.mon27")
require("scripts.Mon.mon28")
require("scripts.Mon.mon32")
require("scripts.Mon.mon37")
require("scripts.Mon.mon39")
require("scripts.Mon.mon43")
require("scripts.Mon.mon54")
require("scripts.Mon.mon59")
require("scripts.Mon.mon61")
require("scripts.Mon.mon62")
require("scripts.Mon.mon64")
require("scripts.Mon.mon65")
require("scripts.Mon.mon66")
require("scripts.Mon.mon68")
require("scripts.Mon.mon70")
require("scripts.Mon.mon81")
require("scripts.Mon.monboss")
require("scripts.Mon.MonGen61")
require("scripts.Mon.mon_zhuansheng")
